os: osx
branches:
  only:
    - master
before_install:
  - python2.7 --version
  - brew update
  - brew install ledger
  - ledger --version
  - brew install python3
  - pip3 install beancount
install: ""
script: ./bin/test.py
notifications:
  email: false
